language: node_js
node_js:
  - 14
services:
  - mysql
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=test
    - DB_HOST='143.198.41.117'
    - DB_USER='admin'
    - DB_PASS='SQLPass1.'
    - DB_NAME='default'
before_script:
  - mysql -e 'CREATE DATABASE test_db;'
script:
  - npm run test